# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AutoReleaseCli < Formula
  desc "Generate release notes automatically with AI-powered templates"
  homepage "https://autoreleasenote.com"
  version "1.0.10-test"

  on_macos do
    on_intel do
      url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.10-test/auto-release-cli_1.0.10-test_darwin_amd64.tar.gz"
      sha256 "abe7882639792103b35879e855c491c53dfd9c0f550735d77cdc76d4d68d4bb0"

      def install
        bin.install "releasenote"
      end
    end
    on_arm do
      url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.10-test/auto-release-cli_1.0.10-test_darwin_arm64.tar.gz"
      sha256 "532cf94aaaaf113a5e4ad79126f7fab071fb1a55f0ff0a85d48b8847ab871544"

      def install
        bin.install "releasenote"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.10-test/auto-release-cli_1.0.10-test_linux_amd64.tar.gz"
        sha256 "2c31af5c47ae11e58c457fd31ceb0e0423fc92be7bd9b49e6f48f6f90c36cb9e"

        def install
          bin.install "releasenote"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.10-test/auto-release-cli_1.0.10-test_linux_arm64.tar.gz"
        sha256 "4b6a1e41a3f924ca02a9739303a461337433a4cbba3e2c5fb3e172f454cb1ad9"

        def install
          bin.install "releasenote"
        end
      end
    end
  end
end
