# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arn < Formula
  desc "Generate release notes automatically with AI-powered templates"
  homepage "https://www.autoreleasenote.com"
  version "1.0.7"

  on_macos do
    on_intel do
      url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.7/arn_1.0.7_darwin_amd64.tar.gz"
      sha256 "a24b7aa45c7a80b4748e84a3badcf0dc7e038e849b00bd347c80e6f6864bb078"

      def install
        bin.install "arn"
      end
    end
    on_arm do
      url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.7/arn_1.0.7_darwin_arm64.tar.gz"
      sha256 "235f91a191261a1452f03f60dda230326e31c4ff81f75b14f924059e3bc2b248"

      def install
        bin.install "arn"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.7/arn_1.0.7_linux_amd64.tar.gz"
        sha256 "85283119514ff175b4c075e8b94dfc9b2709c7bd9ada423a09a4ae90d2240d25"

        def install
          bin.install "arn"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.7/arn_1.0.7_linux_arm64.tar.gz"
        sha256 "d6a795d5d4ae21d59fffcd466cbbf5395d28254c1cf6d0db8a75ed720c04f18c"

        def install
          bin.install "arn"
        end
      end
    end
  end
end
