# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arn < Formula
  desc "Generate release notes automatically with AI-powered templates"
  homepage "https://www.autoreleasenote.com"
  version "1.0.6"

  on_macos do
    on_intel do
      url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.6/arn_1.0.6_darwin_amd64.tar.gz"
      sha256 "10eed5819472ad7ec94886a1f5b8cb0d702c3cfe6092f3f903326347a0460c59"

      def install
        bin.install "arn"
      end
    end
    on_arm do
      url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.6/arn_1.0.6_darwin_arm64.tar.gz"
      sha256 "67f43c6df9d30e4508367d49f046a39b5ba0e352fa1978e4a721c8d9fd22e591"

      def install
        bin.install "arn"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.6/arn_1.0.6_linux_amd64.tar.gz"
        sha256 "9efe2f15473bd2bba9357731ca422f887684e6293f419bd1cc81f20df7b3868f"

        def install
          bin.install "arn"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.6/arn_1.0.6_linux_arm64.tar.gz"
        sha256 "0e4e2a3835feaf8a381d74055161b640c31c85ae2428ef08ede92fbc8a1c5a67"

        def install
          bin.install "arn"
        end
      end
    end
  end
end
