# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arn < Formula
  desc "Generate release notes automatically with AI-powered templates"
  homepage "https://www.autoreleasenote.com"
  version "1.0.8"

  on_macos do
    on_intel do
      url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.8/arn_1.0.8_darwin_amd64.tar.gz"
      sha256 "dc95c20b67ce602ca97b96098cf151877429be4facfdd8a12f4fc9aeed772f77"

      def install
        bin.install "arn"
      end
    end
    on_arm do
      url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.8/arn_1.0.8_darwin_arm64.tar.gz"
      sha256 "6e28e5b31610a5100d1b82c0f79abcd5b019a1b35c9e18cc9fd4993d82a54921"

      def install
        bin.install "arn"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.8/arn_1.0.8_linux_amd64.tar.gz"
        sha256 "2af4f536789945f56a59140adbe30359b6071d57c11aaa267de0f18083ea3e35"

        def install
          bin.install "arn"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.8/arn_1.0.8_linux_arm64.tar.gz"
        sha256 "2fedab4d98a31a0498fdc4e85e9e12ca6a59d6ab02b0184aceeb79c36877312f"

        def install
          bin.install "arn"
        end
      end
    end
  end
end
