# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AutoReleaseCli < Formula
  desc "Generate release notes automatically with AI-powered templates"
  homepage "https://www.autoreleasenote.com"
  version "1.0.17-test"

  on_macos do
    on_intel do
      url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.17-test/auto-release-cli_1.0.17-test_darwin_amd64.tar.gz"
      sha256 "f4ec4a38d0eb7c233eb6dea25c8ee2812b0947426e55c6fc2e781ea668f03940"

      def install
        bin.install "releasenote"
      end
    end
    on_arm do
      url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.17-test/auto-release-cli_1.0.17-test_darwin_arm64.tar.gz"
      sha256 "7f54faa0b5a702ed6030b602dd833c1c7348fdefbd9d5ac0c47187c122804774"

      def install
        bin.install "releasenote"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.17-test/auto-release-cli_1.0.17-test_linux_amd64.tar.gz"
        sha256 "b3eb92a121838ddaafd8f67ea334c79c8abc01129a2808cc615d3e076234fbe0"

        def install
          bin.install "releasenote"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.17-test/auto-release-cli_1.0.17-test_linux_arm64.tar.gz"
        sha256 "52bac8616774a347d056400a98a1cbc635eb9bbf238ce9ebc6f246bfe5ed8ac2"

        def install
          bin.install "releasenote"
        end
      end
    end
  end
end
