# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AutoReleaseCli < Formula
  desc "Generate release notes automatically with AI-powered templates"
  homepage "https://autoreleasenote.com"
  version "1.0.16-test"

  on_macos do
    on_intel do
      url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.16-test/auto-release-cli_1.0.16-test_darwin_amd64.tar.gz"
      sha256 "4013a0df7b79a252dc01a0a65b5dca061cb61ebf0794979d2f54d26f57987701"

      def install
        bin.install "releasenote"
      end
    end
    on_arm do
      url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.16-test/auto-release-cli_1.0.16-test_darwin_arm64.tar.gz"
      sha256 "3dda815f88cd742462dea0aeea4a0d87bced79b3c0aa42cd54a435f893369864"

      def install
        bin.install "releasenote"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.16-test/auto-release-cli_1.0.16-test_linux_amd64.tar.gz"
        sha256 "8baf1ca18af003ea3e51b8fd628bbf5ac524dc9a187e9c2dbab9581f0b9a850e"

        def install
          bin.install "releasenote"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.16-test/auto-release-cli_1.0.16-test_linux_arm64.tar.gz"
        sha256 "c82e4c02790083a712330974aba84a9d1131f9adada3ccf9378c0a33e34589db"

        def install
          bin.install "releasenote"
        end
      end
    end
  end
end
