# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rln < Formula
  desc "Generate release notes automatically with AI-powered templates"
  homepage "https://www.autoreleasenote.com"
  version "1.0.22-test"

  on_macos do
    on_intel do
      url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.22-test/rln_1.0.22-test_darwin_amd64.tar.gz"
      sha256 "200e2325b0a4e121dc4542b4ddd08296a8df315cb271e323aa61950d5aa7c5cc"

      def install
        bin.install "rln"
      end
    end
    on_arm do
      url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.22-test/rln_1.0.22-test_darwin_arm64.tar.gz"
      sha256 "06598028046233eec618a64e8be76913599c0655bba6735a4402a7d464b51118"

      def install
        bin.install "rln"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.22-test/rln_1.0.22-test_linux_amd64.tar.gz"
        sha256 "9b6f81eb081275a2e865f2e945dbfec656d030694d969a6322e1f3ad4faa1ceb"

        def install
          bin.install "rln"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.22-test/rln_1.0.22-test_linux_arm64.tar.gz"
        sha256 "a429f867e90224df2a124db80c9b79f56a7554adf7db9bd1adedb05a750c1c62"

        def install
          bin.install "rln"
        end
      end
    end
  end
end
