# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rln < Formula
  desc "Generate release notes automatically with AI-powered templates"
  homepage "https://www.autoreleasenote.com"
  version "1.0.19-test"

  on_macos do
    on_intel do
      url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.19-test/rln_1.0.19-test_darwin_amd64.tar.gz"
      sha256 "ace1b01711cc853c49d2137774adb8ce2f6bc8c84a3d0b8d8c00d76c398004b0"

      def install
        bin.install "rln"
      end
    end
    on_arm do
      url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.19-test/rln_1.0.19-test_darwin_arm64.tar.gz"
      sha256 "13217393e109ce7c90e24970ece62045806eb03a02bb7e0b58fd5914420d3722"

      def install
        bin.install "rln"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.19-test/rln_1.0.19-test_linux_amd64.tar.gz"
        sha256 "1fedb83b733396114b4075c8b63adfbebe65d24ecf26e659447d2440f2081a5c"

        def install
          bin.install "rln"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.19-test/rln_1.0.19-test_linux_arm64.tar.gz"
        sha256 "5c6683f9ef95e3161afd9c11dc606ab10487f181664429a6a118c0d53f0bfd68"

        def install
          bin.install "rln"
        end
      end
    end
  end
end
