# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rln < Formula
  desc "Generate release notes automatically with AI-powered templates"
  homepage "https://www.autoreleasenote.com"
  version "1.0.21-test"

  on_macos do
    on_intel do
      url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.21-test/rln_1.0.21-test_darwin_amd64.tar.gz"
      sha256 "c0a0eec3bf297c61f0ab414d4af2756f60efe13ce08887826036325146a2b082"

      def install
        bin.install "rln"
      end
    end
    on_arm do
      url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.21-test/rln_1.0.21-test_darwin_arm64.tar.gz"
      sha256 "b4dbcc4ca9adccc3014195b1e80167e7c6ba17f58ccb3d0aec9419d559e7d4ab"

      def install
        bin.install "rln"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.21-test/rln_1.0.21-test_linux_amd64.tar.gz"
        sha256 "ae6cc2a170868e211868a1ca367eb2dbe6439a86e28157dbded702d37e278489"

        def install
          bin.install "rln"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/papyrus-digital/auto-release-cli-distribution/releases/download/v1.0.21-test/rln_1.0.21-test_linux_arm64.tar.gz"
        sha256 "d965e312d7848d07ccbae50b9b19e3bbd0f1b9669ad74a233004f956cd0a45ea"

        def install
          bin.install "rln"
        end
      end
    end
  end
end
